version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mbc320!!
      MYSQL_DATABASE: lms
      MYSQL_USER: mbc
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  flask:
    build: ./flask-app
    container_name: flask
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql

    # 코드 실시간 반영
    volumes:
      - ./flask-app:/app
      - ./flask-app/uploads:/app/uploads

    # GPU 설정 (Compose v2 핵심)
    deploy: {}
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

volumes:
  mysql_data: